spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/e4s?currentSchema=streaming
    username: e4s
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
